name: automerge-main
on:
  workflow_run:
    workflows:
        - Create Release Branch
    types:
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          required-labels: automerge-release-main
          pull-request: ${{ github.event.inputs.pull-request }}