name: automerge-main
on:
  workflow_run:
    workflows:
        - Create Release Branch
    types:
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@v1
        with:
          GITHUB_LOGIN: my-awesome-bot-r2d2
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD : MERGE
