name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true
jobs:
  createrelease:
    runs-on: ubuntu-latest
    name: createrelease and validate
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Create release branch
      run: git checkout -b release/v${{ github.event.inputs.versionName }}
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
    - name: Push new branch
      run: git push origin release/v${{ github.event.inputs.versionName }}
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s tests
    - name: Cálculo de cubrimiento
      id: cubrimiento
      run: |
          coverage run -m unittest discover -s tests
          coverage report -m
  
  pullrequest-main:
    needs: createrelease
    name: Pull request main
    runs-on: ubuntu-latest
    steps:
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: release/v${{ github.event.inputs.versionName }}
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_label: "auto-merge-main"
        pr_title: "v${{ github.event.inputs.versionName }} into main"
        pr_body: "Este PR fue creado ya que las pruebas en Release se ejecutaron exitosamente."
    - name: output-url
      run: echo ${{steps.open-pr.outputs.pr_url}}
    - name: output-number
      run: echo ${{steps.open-pr.outputs.pr_number}}
    - name: output-has-changed-files
      run: echo ${{steps.open-pr.outputs.has_changed_files}}

  automerge:
    name: Automerge
    needs: pullrequest-main
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@4536e8847eb62fe2f0ee52c8fa92d17aa97f932f"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "auto-merge-main"