name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true
jobs:
  createrelease:
    runs-on: ubuntu-latest
    name: createrelease and validate
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Create release branch
      run: git checkout -b release/v${{ github.event.inputs.versionName }}
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
    - name: Push new branch
      run: git push origin release/v${{ github.event.inputs.versionName }}
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s tests
    - name: Cálculo de cubrimiento
      id: cubrimiento
      run: |
          coverage run -m unittest discover -s tests
          coverage report -m
  
  pullrequest-main:
    needs: createrelease
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
    - name: Create pull request into main
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       head: release/v${{ github.event.inputs.versionName }}
       base: main
       title: v${{ github.event.inputs.versionName }} into main
       reviewers: ${{ github.event.issue.user.login }}
       body: |
           Hola!
           Este PR fue creado ya que las pruebas en Release se ejecutaron exitosamente.

  pullrequest-develop:
    needs: createrelease
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
    - name: Create pull request to develop
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release/v${{ github.event.inputs.versionName }}
          base: develop
          title: v${{ github.event.inputs.versionName }} into develop
          reviewers: ${{ github.event.issue.user.login }}
          body: |
              Hola!
              Este PR fue creado ya que las pruebas en Release se ejecutaron exitosamente.